#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "beautifulsoup4>=4.13,<5",
#   "requests>=2.32,<3",
# ]
# ///
"""Refresh the checked-in BG3 spell-choice catalog from bg3.wiki."""

from __future__ import annotations

import json
import pathlib
import re
import time

import requests
from bs4 import BeautifulSoup


ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "mac/BG3Assistant/BG3SpellCatalog.generated.swift"
CLASSES = ("Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard")
LEVELS = {"C": 0, **{str(level): level for level in range(1, 7)}}


def fetch_spells(class_name: str) -> dict[int, list[str]]:
    url = f"https://bg3.wiki/w/index.php?title=List_of_{class_name}_spells&printable=yes"
    for retry in range(5):
        response = requests.get(url, timeout=30, headers={"User-Agent": "BG3Overlay/1.0"})
        if response.status_code != 429:
            break
        time.sleep(2 ** (retry + 1))
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    heading = next(
        item for item in soup.select("h2")
        if item.get_text(" ", strip=True).lower() == f"{class_name.lower()} spell list"
    )
    table = heading.find_next("table")
    result: dict[int, list[str]] = {level: [] for level in range(7)}
    for row in table.select("tr")[1:]:
        cells = row.select("th,td")
        if len(cells) < 2:
            continue
        name = re.sub(r" \((?:spell|Cantrip)\)$", "", cells[0].get_text(" ", strip=True))
        level = LEVELS.get(cells[1].get_text(" ", strip=True))
        if name and level is not None and name not in result[level]:
            result[level].append(name)
    return result


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    lines = [
        "// Generated by scripts/macos/fetch-class-spells.py from bg3.wiki.",
        "// Source pages are CC BY-SA; see THIRD_PARTY_NOTICES.md.",
        "import Foundation",
        "",
        "enum BG3SpellCatalog {",
        "    static let byClassAndRank: [String: [Int: [String]]] = [",
    ]
    for class_name in CLASSES:
        lines.append(f"        {swift_string(class_name)}: [")
        for level, names in fetch_spells(class_name).items():
            joined = ", ".join(swift_string(name) for name in names)
            lines.append(f"            {level}: [{joined}],")
        lines.append("        ],")
        time.sleep(1)
    lines += [
        "    ]",
        "",
        "    static func spells(for className: String, from minimumRank: Int = 0, through maximumRank: Int) -> [String] {",
        "        guard let ranks = byClassAndRank[className] else { return [] }",
        "        return ranks.keys.filter { $0 >= minimumRank && $0 <= maximumRank }.sorted().flatMap { ranks[$0] ?? [] }",
        "    }",
        "}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
