<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>GameWindowHost</AssemblyName>
    <RootNamespace>GameWindowHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BG3HonorAssistant.Windows\BG3HonorAssistant.Windows.csproj" />
  </ItemGroup>
</Project>
